const MICROSOFT_KEYWORDS = {
  cloudServices: [
    'azure',
    'cloud',
    'computação em nuvem',
    'cloud computing',
    'nuvem',
    'saas',
    'paas',
    'iaas',
    'microsoft cloud',
    'serviços cloud',
    'armazenamento cloud',
  ],
  software: [
    'microsoft',
    'office 365',
    'microsoft 365',
    'm365',
    'teams',
    'sharepoint',
    'onedrive',
    'outlook',
    'windows',
    'licença',
    'licenças',
    'licenciamento',
    'software',
    'aplicações',
    'word',
    'excel',
    'powerpoint',
    'access',
    'visio',
    'project',
  ],
  itServices: [
    'transformação digital',
    'digitalização',
    'modernização',
    'tecnologia de informação',
    'tecnologias de informação',
    'ti ',
    'tic',
    'suporte técnico',
    'helpdesk',
    'service desk',
    'consultoria ti',
    'implementação',
    'migração',
    'integração',
  ],
  enterpriseSolutions: [
    'dynamics',
    'crm',
    'erp',
    'gestão empresarial',
    'business intelligence',
    'power bi',
    'power apps',
    'power automate',
    'power platform',
    'azure devops',
    'github',
    'analytics',
    'inteligência artificial',
    'machine learning',
    'ia ',
    'copilot',
  ],
  infrastructure: [
    'servidor',
    'servidores',
    'infraestrutura',
    'rede',
    'datacenter',
    'data center',
    'backup',
    'segurança informática',
    'cibersegurança',
    'active directory',
    'hyper-v',
    'virtualização',
    'windows server',
  ],
  general: [
    'informática',
    'tecnologia',
    'digital',
    'sistema informático',
    'plataforma digital',
    'portal',
    'aplicação web',
    'base de dados',
    'sql',
  ],
};

module.exports = { MICROSOFT_KEYWORDS };
